server:
  port: 9094

spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "secret"
  profiles:
    active: local
  application:
    name: PROFILE-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/social
      host: localhost
      port: 27017
      database: social
      repositories:
        enabled: true
