server:
  port: 9094

spring:
  profiles:
    active: local
  application:
    name: PROFILE-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/social
      host: localhost
      port: 27017
      database: social
      repositories:
        enabled: true
